//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArrayOrdenPreguntas
    {
        public int IdArrayOrdenPreguntas { get; set; }
        public int p01 { get; set; }
        public int p02 { get; set; }
        public int p03 { get; set; }
        public int p04 { get; set; }
        public int p05 { get; set; }
        public int p06 { get; set; }
        public int p07 { get; set; }
        public int p08 { get; set; }
        public int p09 { get; set; }
        public int p10 { get; set; }
        public int p11 { get; set; }
        public int p12 { get; set; }
        public int p13 { get; set; }
        public int p14 { get; set; }
        public int p15 { get; set; }
        public int p16 { get; set; }
        public int p17 { get; set; }
        public int p18 { get; set; }
        public int p19 { get; set; }
        public int p20 { get; set; }
        public int p21 { get; set; }
        public int p22 { get; set; }
        public int p23 { get; set; }
        public int p24 { get; set; }
        public int p25 { get; set; }
        public int p26 { get; set; }
        public int p27 { get; set; }
        public int p28 { get; set; }
        public int p29 { get; set; }
        public int p30 { get; set; }
        public int p31 { get; set; }
        public int p32 { get; set; }
        public int p33 { get; set; }
        public int p34 { get; set; }
        public int p35 { get; set; }
        public int p36 { get; set; }
        public int p37 { get; set; }
        public int p38 { get; set; }
        public int p39 { get; set; }
        public int p40 { get; set; }
        public int p41 { get; set; }
        public int p42 { get; set; }
        public int p43 { get; set; }
        public int p44 { get; set; }
        public int p45 { get; set; }
        public int p46 { get; set; }
        public int p47 { get; set; }
        public int p48 { get; set; }
        public int p49 { get; set; }
        public int p50 { get; set; }
        public int ExamenIdExamen { get; set; }
    }
}
