//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleExamen
    {
        public int IdDetalleExamen { get; set; }
        public string Pregunta1 { get; set; }
        public string Pregunta2 { get; set; }
        public string Pregunta3 { get; set; }
        public string Pregunta4 { get; set; }
        public string Pregunta5 { get; set; }
        public string Pregunta6 { get; set; }
        public string Pregunta7 { get; set; }
        public string Pregunta8 { get; set; }
        public string Pregunta9 { get; set; }
        public string Pregunta10 { get; set; }
        public string Pregunta11 { get; set; }
        public string Pregunta12 { get; set; }
        public string Pregunta13 { get; set; }
        public string Pregunta14 { get; set; }
        public string Pregunta15 { get; set; }
        public string Pregunta16 { get; set; }
        public string Pregunta17 { get; set; }
        public string Pregunta18 { get; set; }
        public string Pregunta19 { get; set; }
        public string Pregunta20 { get; set; }
        public string Pregunta21 { get; set; }
        public string Pregunta22 { get; set; }
        public string Pregunta23 { get; set; }
        public string Pregunta24 { get; set; }
        public string Pregunta25 { get; set; }
        public string Pregunta26 { get; set; }
        public string Pregunta27 { get; set; }
        public string Pregunta28 { get; set; }
        public string Pregunta29 { get; set; }
        public string Pregunta30 { get; set; }
        public string Pregunta31 { get; set; }
        public string Pregunta32 { get; set; }
        public string Pregunta33 { get; set; }
        public string Pregunta34 { get; set; }
        public string Pregunta35 { get; set; }
        public string Pregunta36 { get; set; }
        public string Pregunta37 { get; set; }
        public string Pregunta38 { get; set; }
        public string Pregunta39 { get; set; }
        public string Pregunta40 { get; set; }
        public int ExamenIdExamen { get; set; }
    }
}
