//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examen
    {
        public int IdExamen { get; set; }
        public string NombreExamen { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> Avance { get; set; }
        public int AlumnoIdAlumno { get; set; }
        public string NumeroDePreguntas { get; set; }
    
        public virtual DetalleExamen DetalleExaman { get; set; }
    }
}
