//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntajePregunta
    {
        public int IdPuntajePreguntas { get; set; }
        public string sp1 { get; set; }
        public string sp2 { get; set; }
        public string sp3 { get; set; }
        public string sp4 { get; set; }
        public string sp5 { get; set; }
        public int ExamenIdExamen { get; set; }
    }
}
